# Default values for mojaloop-simulator-core-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pm4ml/mojaloop-payment-manager-simulator-core-connector
  tag: 1.4.5
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

#### ENV values
env:
  BACKEND_ENDPOINT: http://localhost:3002
  MLCONN_OUTBOUND_ENDPOINT: http://localhost:4001
envFromSecrets:
#  API_KEY:
#    secret:
#      name: some-secret-name
#      key: API_KEY
#  API_SECRET:
#    secret:
#      name: another-secret-name
#      key: API_SECRET

ports:
  - port: http
    portNumber: 3003
    targetPort: http
    protocol: TCP
    serviceEnabled: true

livenessProbe:
  enabled: true
  path: /health
  port: http

readinessProbe:
  enabled: true
  path: /health
  port: http

service:
  type: ClusterIP
  # this is the port the SERVICE will listen on. requests to the service address on this port
  # get mapped to the "http" named port on the deployment

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: "/"
          servicePort: http

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  # secretName1:
  #   key1: "value"
  #   key2: "value"
  # secretName2:
  #   key1: "value"
  #   key2: "value"
