apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pm4ml-mojaloop-connector.fullname" . }}
  labels:
{{ include "pm4ml-mojaloop-connector.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pm4ml-mojaloop-connector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pm4ml-mojaloop-connector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullCredentials }}
      imagePullSecrets:
        - name: {{ include "pm4ml-mojaloop-connector.fullname" . }}-cred
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{if not (hasKey .Values.env "CACHE_HOST") }}
            - name: CACHE_HOST
              value: {{ printf "%s-cache" ( include "pm4ml-mojaloop-connector.fullname" . ) }}
            {{ end }}
            {{if not (hasKey .Values.env "BACKEND_ENDPOINT") }}
            - name: BACKEND_ENDPOINT
              value: {{ printf "%s-backend:3000" ( include "pm4ml-mojaloop-connector.fullname" . ) }}
            {{ end }}              
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          ports:
            - name: inboundapi
              containerPort: {{ .Values.env.INBOUND_LISTEN_PORT }}
              protocol: TCP
            - name: outboundapi
              containerPort: {{ .Values.env.OUTBOUND_LISTEN_PORT }}
              protocol: TCP
            - name: testapi
              containerPort: {{ .Values.env.TEST_LISTEN_PORT }}
              protocol: TCP
            - name: websocket
              containerPort: {{ .Values.env.WS_PORT }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.env.METRICS_SERVER_LISTEN_PORT }}
              protocol: TCP
          volumeMounts:
          - name: jws-public-keys
            mountPath: {{ .Values.env.JWS_VERIFICATION_KEYS_DIRECTORY }}
          {{- if .Values.env.JWS_SIGN }}
          - name: jws-private-key
            mountPath: "/jwsSigningKey/"
          {{- end }}
          - name: tls-secrets
            mountPath: "/secrets/"  
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.env.OUTBOUND_LISTEN_PORT }}
              scheme: HTTP
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.env.OUTBOUND_LISTEN_PORT }}
              scheme: HTTP
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.env.JWS_SIGN }}
      - name: jws-private-key
        secret:
          {{- if .Values.secrets.jws.privKeySecretName }}
          secretName: {{ .Values.secrets.jws.privKeySecretName }}
          {{- else }}
          secretName: {{ include "pm4ml-mojaloop-connector.fullname" . }}-jws-priv-key
          {{- end }}
      {{- end }}
      - name: jws-public-keys
        configMap:
          {{- if .Values.secrets.jws.publicKeyConfigMapName }}
          name: {{ .Values.secrets.jws.publicKeyConfigMapName }}
          {{- else }}
          name: {{ include "pm4ml-mojaloop-connector.fullname" . }}-jws-public-keys
          {{- end }}
      - name: tls-secrets
        secret:
          {{- if .Values.secrets.tlsSecretName }}
          secretName: {{ .Values.secrets.tlsSecretName }}
          {{- else }}
          secretName: {{ include "pm4ml-mojaloop-connector.fullname" . }}-tls-creds
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
